// <auto-generated />
using System;
using GameManager.WebApp.BS.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameManager.WebApp.BS.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230710093719_first_migration")]
    partial class first_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameGameCollection", b =>
                {
                    b.Property<int>("GameCollectionsId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.HasKey("GameCollectionsId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameGameCollection");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.ApiAccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyVaultSecretId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId1")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId1");

                    b.ToTable("ApiAccessToken");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDateOfGame")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameCategory");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.GameCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DispleyIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispleyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameCollection");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.GameSubCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GameCollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameCollectionId");

                    b.ToTable("GameSubCollection");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCategoryId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IUserCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IUserCategoryId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtLastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionId1")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCategory")
                        .HasColumnType("int");

                    b.Property<int>("UserCategoryNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubscriptionId1");

                    b.HasIndex("UserCategoryNavigationId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.UserCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCategory");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatus");
                });

            modelBuilder.Entity("GameGameCollection", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.GameCollection", null)
                        .WithMany()
                        .HasForeignKey("GameCollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameManager.WebApp.BS.Entities.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.ApiAccessToken", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.Subscription", "Subscription")
                        .WithMany("ApiAccessTokens")
                        .HasForeignKey("SubscriptionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Device", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.Game", null)
                        .WithMany("Devices")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Game", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.GameCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.GameSubCollection", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.GameCollection", null)
                        .WithMany("GameSubCollections")
                        .HasForeignKey("GameCollectionId");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Role", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.UserCategory", "UserCategory")
                        .WithMany("Roles")
                        .HasForeignKey("UserCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCategory");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Subscription", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.UserCategory", "IUserCategory")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IUserCategoryId");

                    b.Navigation("IUserCategory");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.User", b =>
                {
                    b.HasOne("GameManager.WebApp.BS.Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("GameManager.WebApp.BS.Entities.Models.UserStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameManager.WebApp.BS.Entities.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId1");

                    b.HasOne("GameManager.WebApp.BS.Entities.Models.UserCategory", "UserCategoryNavigation")
                        .WithMany("Users")
                        .HasForeignKey("UserCategoryNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("Subscription");

                    b.Navigation("UserCategoryNavigation");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Game", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.GameCollection", b =>
                {
                    b.Navigation("GameSubCollections");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.Subscription", b =>
                {
                    b.Navigation("ApiAccessTokens");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.UserCategory", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Subscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GameManager.WebApp.BS.Entities.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
